### PR TITLE
More flexible asset naming

### PR DESCRIPTION
**Pull request by dgvirtual**
with a custom busting separator
(allowing for multiple dots in file names)
implementing proposal "More flexible asset naming?" #408

### CODE REVIEW

**Comment by datamweb** [comment]
@dgvirtual I have send a PR #411 , please check if you can.

**Comment by dgvirtual** [comment]
> @dgvirtual I have send a PR #411 , please check if you can.

I see it is merged already. Did some style changes to rerun tests on my PR. Still some failures, though unrelated to my PR...

**Comment by datamweb** [comment]
Please rebase:

```console
git fetch upstream
git switch develop
git merge upstream/develop
git switch improve-assets
git rebase upstream/develop
git push --force-with-lease origin improve-assets
```
I don't see anything after rebase, of course I'm on PHP 8.3.
```
P:\MyGitHubWork\Bonfire2>php vendor/bin/phpunit
PHPUnit 9.6.15 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.3.0RC6 with Xdebug 3.3.0alpha3
Configuration: P:\MyGitHubWork\Bonfire2\phpunit.xml.dist

...............................................................  63 / 106 ( 59%)
...........................................                     106 / 106 (100%)

Nexus\PHPUnit\Extension\Tachycardia identified these 14 slow tests:
+----------------------------------------------------------------------+---------------+-------------+
| Test Case                                                            | Time Consumed | Time Limit  |
+----------------------------------------------------------------------+---------------+-------------+
| Tests\\Auth\\RegisterTest::testRegisterSuccess                       | 00:00:01.04   | 00:00:00.50 |
| Tests\\Auth\\RegisterTest::testRedirectsToEmailActivationScreen      | 00:00:01.04   | 00:00:00.50 |
| Tests\\Recycler\\RecyclerTest::testIndexShowsDeletedUsers            | 00:00:00.72   | 00:00:00.50 |
| Tests\\Auth\\AdminAccessTest::testAdminsCanAccess                    | 00:00:00.70   | 00:00:00.50 |
| Tests\\Groups\\GroupsTest::testCanSeeGroupPermissions                | 00:00:00.56   | 00:00:00.50 |
| Tests\\Auth\\AdminAccessTest::testCannotAccessAdminWithoutPermission | 00:00:00.53   | 00:00:00.50 |
| Tests\\Groups\\GroupsTest::testCanSaveGroup                          | 00:00:00.53   | 00:00:00.50 |
| Tests\\Groups\\GroupsTest::testCanSaveGroupPermissions               | 00:00:00.53   | 00:00:00.50 |
| Tests\\Menus\\MenuCollectionTest::testHasVisibleItems                | 00:00:00.53   | 00:00:00.50 |
| Tests\\Settings\\SiteOfflineTest::testAllWhenOn                      | 00:00:00.52   | 00:00:00.50 |
| Tests\\Auth\\LoginTest::testLoginSuccessAdmin                        | 00:00:00.52   | 00:00:00.50 |
| Tests\\Auth\\LoginTest::testLoginTo2FAAction                         | 00:00:00.52   | 00:00:00.50 |
| Tests\\Settings\\SiteOfflineTest::testOnlySuperAdminWhenOff          | 00:00:00.52   | 00:00:00.50 |
| Tests\\Auth\\LoginTest::testLoginSuccess                             | 00:00:00.51   | 00:00:00.50 |
+----------------------------------------------------------------------+---------------+-------------+


Time: 00:22.381, Memory: 38.00 MB

OK (106 tests, 277 assertions)
```

**Comment by dgvirtual** [comment]
Thanks, did it.
Ok, so now only one test (phpunit, php8.1) fails (though mine got passed on local machine), and phpunit for 8.2 is cancelled for no apparent reason...

**Comment by dgvirtual** [comment]
> @dgvirtual I have send a PR #411 , please check if you can.

By the way, how would I take a PR you submitted and apply it to my fork to test? Could you give me some hints at least what to Google for?

**Comment by dgvirtual** [comment]
As I see it, the phpunit tests related to my changes are passing with all php versions (the problems are potentially in other parts of codebase). If my PR is ok, I expect it to be merged before continuing work on defer/async and other possible attributes for the assets helper.

**Review by lonnieezell — APPROVED** [review]
Looks good. Thanks!

**Pull request merged**
