### PR TITLE
Fix for limiting logins list length

### PR DESCRIPTION
**Pull request by dgvirtual**
(Codeigniter Model does not implement limit() metod

### CODE REVIEW

**Comment by lonnieezell** [comment]
The `Model` class doesn't directly, but it can use most of the functions from the query builder chained like that. Were you running into an actual error with this?

**Comment by dgvirtual** [comment]
> The `Model` class doesn't directly, but it can use most of the functions from the query builder chained like that. Were you running into an actual error with this?

Using limit() does not produce an error, but it does not work either, it has no effect (on CI 4.3.3, php 7.4).

**Comment by dgvirtual** [comment]
@lonnieezell, I did a rebase for this PR, so now it passes tests. Please consider it as well. It is only minor improvement, but does limit the otherwise endless list of recent logins (https://www.codeigniter.com/user_guide/models/model.html#findall)

**Review by lonnieezell — APPROVED** [review]
Good call. Thanks!

**Comment by kenjis** [comment]
Oh, the the query builder `limit(20)` is overwritten by `$limit` of `findAll()`!

**Comment by dgvirtual** [comment]
Explains why limit() neither fails nor has any effect...

**Comment by dgvirtual** [comment]
If all is fine, could someone merge this into develop please? @lonnieezell ?

**Comment by dgvirtual** [comment]
@lonnieezell , let's finish this trivial change.

**Review by kenjis — APPROVED** [review]

**Pull request merged**
