### PR TITLE
 Remove .log from log review urls

### PR DESCRIPTION
**Pull request by dgvirtual**
as some servers block .log extensions
update localization
update test

### CODE REVIEW

**Comment by lonnieezell** [comment]
Please address the static analysis error and we can merge.

**Comment by dgvirtual** [comment]
OK, I see where the problem is. Never used phpstan before, but I did some exploration and this shows how useful it can be. I will modify my modifications :), so I imagine "squash and merge" should be used. Later today.... [edit] DONE

**Comment by dgvirtual** [comment]
> Please address the static analysis error and we can merge.

@lonnieezell, how do I find how to run all the tests that are set up for this project? Any documentation I should read? I am only starting with testing...

**Comment by lonnieezell** [comment]
Thanks! Merging.

**Pull request merged**
