### PR TITLE
Fix current page link(pagination) was not getting "active".

### PR DESCRIPTION
**Pull request by kgrruz**

### CODE REVIEW

**Comment by lonnieezell** [comment]
Please separate the logs viewer page into its own PR. Keeping them separated makes it easier to review and doesn't hold up on thing from being merged because of issues with another thing.

**Comment by kgrruz** [comment]
OK. I opened a new pull request but github merged the two requests/changes.

**Comment by lonnieezell** [comment]
If they're in the same branch GitHub will do that. Each one needs to be in its own branch.

**Comment by kgrruz** [comment]
Thanks for the explanation.

**Pull request closed without merging**
