### PR TITLE
- Fix user settings

### PR DESCRIPTION
**Pull request by atsanna**
I noticed that the administrative page for user settings does not save the settings - I think I have solved the problem

### CODE REVIEW

**Comment by lonnieezell** [comment]
This looks to have some conflicts. Can you resolve those, please?

**Comment by atsanna** [comment]
Sorry, it should be fine now :)

**Comment by lonnieezell** [comment]
Did you run `composer style` on this? It's changing everything from spaces to tabs and I'm pretty sure the settings in the style fixer should be spaces. 

Either way, please use spaces for this project.

**Comment by atsanna** [comment]
> Did you run `composer style` on this? It's changing everything from spaces to tabs and I'm pretty sure the settings in the style fixer should be spaces.
> 
> Either way, please use spaces for this project.

I am running composer style multiple times before each commit.
I run compose style until the command line returns this message.
```shell
~/Documenti/Projects/atsanna_bonfire2$ composer style
> php-cs-fixer fix --verbose --ansi --using-cache=no
PHP CS Fixer 3.3.2 Trinacria by Fabien Potencier and Dariusz Ruminski
Runtime: PHP 8.0.8
Loaded config CodeIgniter4 Coding Standards from "/home/antonio/Documenti/Projects/atsanna_bonfire2/.php-cs-fixer.dist.php".
...............................................................................................................................................
Legend: ?-unknown, I-invalid file syntax (file ignored), S-skipped (cached or empty file), .-no changes, F-fixed, E-error

Fixed all files in 1.832 seconds, 16.000 MB memory used
antonio@HP-ZBook-15-G6:~/Documenti/Projects/atsanna_bonfire2$ 
```
I started using PhpStorm 2021.3 running on Ubuntu 20.10 a few months ago: I will try to check if by chance there is some setting that ruins everything ...

**Comment by atsanna** [comment]
I think I found a setting in the editor where the tab character was set.

I hope I have solved the problem.

I tried to manually fix all files that used tab.

Sorry for that.

**Comment by lonnieezell** [comment]
No worries. thanks for this! Merging

**Pull request merged**
